name: Captain Kube CI/CD

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Build Docker Image
        run: docker build -t captain-kube-tests .
      
      - name: Run Unit Tests in Docker
        run: docker run --rm captain-kube-tests

  build_release:
    name: Build and Release Binary
    runs-on: ubuntu-latest
    needs: test  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel pyinstaller
      
      - name: Build Binary with PyInstaller
        run: |
          pyinstaller --onefile --name captain-kube captain_kube.py
          mv dist/captain-kube captain-kube
      
      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: captain-kube
          path: captain-kube

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build_release 
    steps:
      - name: Download Binary Artifact
        uses: actions/download-artifact@v4
        with:
          name: captain-kube
          path: ./
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: captain-kube
          tag_name: v1.0.${{ github.run_number }}
          name: "Captain Kube v1.0.${{ github.run_number }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.RT }}